version: '3'
services: 
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment: 
      - discovery.type=single-node
    volumes: 
      - ./data/elastic:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: kibana
    ports: 
      - "5601:5601"
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on: 
      - elastic
    links: 
      - elastic:elasticsearch
    
  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    container_name: logstash
    volumes: 
      - ./data/log:/var/tmp/log/
      - ./config/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on: 
      - elastic
    links: 
      - elastic:elasticsearch
    
    